### ISSUE TITLE
Incrementing vruntime

### ISSUE THREAD

**Issue by liorze** [nihal111/CFS-visualizer#9]
Hello,

In `scheduler.js` vruntime is incremented by `1024/(1000*running_task.slice)`, but as far as I understand CFS it should be incremented by `1024/running_task.weight`. Can you please explain that line?

Thank you

**Comment by nihal111** [comment]
Hey @liorze 

Good catch. This repository was for a course project and is more than a year old at this point. I'm really rusty on the details. But from what I recollect, the overall update for `vruntime` is defined as follows-
`vruntime += (running_task.slice * 1024)/(running_task.weight)`

Since the update for `vruntime` in our implementation is defined at every "tick" (every call to `nextIteration`), we update `vruntime` a total of `running_task.slice` times.

Which would mean the vruntime update is correctly what you suggest-
`vruntime += 1024/running_task.weight`

Does this look correct to you?
If it does, would you like to send a patch to fix it? :slightly_smiling_face:

**Comment by liorze** [comment]
Sure, I just opened a PR. #10 
I also added a condition checking that a task is run for at least `min_granularity` ms.
